name 'scheduled_run_list'
maintainer 'Matt Ray'
maintainer_email 'matt@chef.io'
license 'Apache-2.0'
description 'Schedules a run list for running within a time window'
version '0.2.0'
chef_version '>= 15.0'

issues_url       'https://github.com/mattray/scheduled_run_list-cookbook/issues'
source_url       'https://github.com/mattray/scheduled_run_list-cookbook'
